2025-06-30 11:58:44,706 INFO     Data loading | DONE!
entity size:  8673
relation size:  20
Traceback (most recent call last):
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/run_rnnlogic.py", line 259, in <module>
    main(parse_args())
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/run_rnnlogic.py", line 94, in main
    dataset = RuleDataset(graph.relation_size, cfg.data.rule_file, cfg.data.cluster_size, cfg.data.relation_cluster_file)
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/data/rules_dataset.py", line 27, in __init__
    self.rel2cluster   = load_relation_clusters(rel_cluster_file)
  File "/home/emma/emma/bilab_archive/polly/RNNLogic/src/data/rules_dataset.py", line 9, in load_relation_clusters
    with open(path) as fi:
FileNotFoundError: [Errno 2] No such file or directory: '../data/semmeddb/relation_cluster/matrix_3.dict'
